# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a87c8d937f022aa4e15f93879aaeec1de35c20a8adaddbb0e098d93b75dc6d36cba84e107e4fd04584ab81b44b403f1d2bd0e05c548b40863456dce8571c547

test:
  secret_key_base: 0c5efd18130d26a6b9755b7d9f9847dfb771057b25f6853291e55e55de0fdb5cca090c83efca76ab5db3612ce3174b77217f28a8d2725b59686b2c4c7e90eed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
